### ISSUE TITLE
jenkins do not act on "Release"

### ISSUE THREAD

**Issue by danielecr** [jenkinsci/gogs-webhook-plugin#34]
![only_release](https://user-images.githubusercontent.com/2484638/37241226-031e4ba2-2456-11e8-817e-5e347f1e3b60.png)
When selected only release on gogs webhook, jenkins does not undersand and does not start pipeline.
When selected "Push" them it works.
I release by:

```
git tag vXX
git push --tags
```

**Comment by sanderv32** [comment]
Are you sure this is a `gogs-webhook-plugin` problem and not a gogs problem? Tested it myself but with the release checkbox checked no webhook is triggered. TCPDUMP also didn't show up any packets on the webhook, so I suspect `gogs` is the problem.

**Comment by sanderv32** [comment]
Investigated the problem but Gogs isn't triggering the webhook. This issue is also reported here [#5042](https://github.com/gogits/gogs/issues/5042). Secondly until now we only trigger on push events, see line 104 in the file [GogsWebHook.java](https://github.com/jenkinsci/gogs-webhook-plugin/blob/master/src/main/java/org/jenkinsci/plugins/gogs/GogsWebHook.java#L104). If the Gogs issue is solved we can take a look if we can implement this in this webhook. Will close this issue.
